print("Chat Bot")
print("What's your name sir?")
a=input()
print("As you tell sir your name is",a)
print("What's your favourite color?")
ab=input()
print("your favourite color is",ab)
print("What's your favourite sport?")
user=input()
print("Your favourite sport is",user)
print("What's your age?")
bc=input()
print("Your age is",bc)